name: Automatically update lock files

on:
  schedule:
    - cron: "30 4 1 * *"  # runs on the 1st of every month at 4:30 UTC
  workflow_dispatch:

jobs:
  lockfile-update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5.0.0
      - name: Install rust
        uses: dtolnay/rust-toolchain@stable
      - name: Install Nix
        uses: cachix/install-nix-action@v31
      - name: Cargo update
        run: |
          cargo update --config 'resolver.incompatible-rust-versions="fallback"'
          cd test
          cargo update --config 'resolver.incompatible-rust-versions="fallback"'
      - name: Nix update
        run: |
          nix flake update
      - name: Create pull request
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.GH_TOKEN_FOR_UPDATES }}
          commit-message: Update lockfiles
          title: "[Automated] Update lockfiles"
          branch: automated/lockfile-update
          body: >
            This is an auto-generated PR running `cargo update` and `nix flake update`
